project:
  type: website
  output-dir: docs

website:
  title: "Em Ragaine"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - experience.qmd

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true

editor: visual

